name: Deploy static content to Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rust Cache
        id: cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: |
            ~/.cache/wasm-pack/
      - name: Inspect Cache
        run: |
          echo "~/.cargo/:"
          ls ~/.cargo/ || true
          echo "./target/:"
          ls ./target/ || true
          echo "~/.cache/wasm-pack/:"
          ls ~/.cache/wasm-pack/ || true
      - name: Install WASM Tools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall wasm-pack
      - name: Build WASM
        run: wasm-pack build --target web --no-pack
      - name: Move Files
        run: |
          mkdir site
          mv pkg/ index.html index.js style.css site/
      - name: Setup Pages # May be unuseful?
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site/"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
